services:
  api:
    build: .
    container_name: aspes
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:password@db:5432/postgres
    depends_on:
      db:
        condition: service_healthy
    command: >
        sh -c "pwd && ls -la && uv run alembic -c /code/alembic.ini upgrade head &&
        uv run fastapi run main.py --port 8000"

  db:
    image: postgres:17.2
    container_name: aspes-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: